# Generated by Django 4.1.12 on 2024-04-16 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('item', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/model')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userinfo')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
